services:
  qbittorrent:
    image: ghcr.io/thelovinator1/qbittorrent:master
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
      - "47273:47273/udp"
      - "47273:47273/tcp"
      - "9000:9000/tcp"
      - "9000:9000/udp"
    volumes:
      - downloads:/downloads
      - data:/home/qbittorrent/.local/share/qBittorrent
      - config:/home/qbittorrent/.config/qBittorrent
volumes:
  downloads:
  data:
  config:
